export const ADD_TO_GALLERY_REQUEST = "ADD_TO_GALLERY_REQUEST";
export const ADD_TO_GALLERY_SUCCESS = "ADD_TO_GALLERY_SUCCESS";
export const ADD_TO_GALLERY_FAIL = "ADD_TO_GALLERY_FAIL";

export const GET_MY_GALLERY_REQUEST = "GET_MY_GALLERY_REQUEST";
export const GET_MY_GALLERY_SUCCESS = "GET_MY_GALLERY_SUCCESS";
export const GET_MY_GALLERY_FAIL = "GET_MY_GALLERY_FAIL";

export const GET_SCHOOL_GALLERY_REQUEST = "GET_SCHOOL_GALLERY_REQUEST";
export const GET_SCHOOL_GALLERY_SUCCESS = "GET_SCHOOL_GALLERY_SUCCESS";
export const GET_SCHOOL_GALLERY_FAIL = "GET_SCHOOL_GALLERY_FAIL";
