export const INITIALIZE_PAYMENT_REQUEST = "INITIALIZE_PAYMENT_REQUEST";
export const INITIALIZE_PAYMENT_SUCCESS = "INITIALIZE_PAYMENT_SUCCESS";
export const INITIALIZE_PAYMENT_FAIL = "INITIALIZE_PAYMENT_FAIL";
