export const GET_ALL_SCHOOLS_REQUEST = "GET_ALL_SCHOOLS_REQUEST";
export const GET_ALL_SCHOOLS_SUCCESS = "GET_ALL_SCHOOLS_SUCCESS";
export const GET_ALL_SCHOOLS_FAIL = "GET_ALL_SCHOOLS_FAIL";

export const SEARCH_SCHOOLS_REQUEST = "SEARCH_SCHOOLS_REQUEST";
export const SEARCH_SCHOOLS_SUCCESS = "SEARCH_SCHOOLS_SUCCESS";
export const SEARCH_SCHOOLS_FAIL = "SEARCH_SCHOOLS_FAIL";

export const UPDATE_SCHOOL_REQUEST = "UPDATE_SCHOOL_REQUEST";
export const UPDATE_SCHOOL_SUCCESS = "UPDATE_SCHOOL_SUCCESS";
export const UPDATE_SCHOOL_FAIL = "UPDATE_SCHOOL_FAIL";

export const FEATURED_SCHOOLS_REQUEST = "FEATURED_SCHOOLS_REQUEST";
export const FEATURED_SCHOOLS_SUCCESS = "FEATURED_SCHOOLS_SUCCESS";
export const FEATURED_SCHOOLS_FAIL = "FEATURED_SCHOOLS_FAIL";
