export const SCHOOL_SIGNIN_REQUEST = "SCHOOL_SIGNIN_REQUEST";
export const SCHOOL_SIGNIN_SUCCESS = "SCHOOL_SIGNIN_SUCCESS";
export const SCHOOL_SIGNIN_FAIL = "SCHOOL_SIGNIN_FAIL";

export const SCHOOL_SIGNUP_REQUEST = "SCHOOL_SIGNUP_REQUEST";
export const SCHOOL_SIGNUP_SUCCESS = "SCHOOL_SIGNUP_SUCCESS";
export const SCHOOL_SIGNUP_FAIL = "SCHOOL_SIGNUP_FAIL";

export const SCHOOL_SIGNOUT = "USER_SIGNOUT";
