export const CREATE_BLOG_REQUEST = "CREATE_BLOG_REQUEST";
export const CREATE_BLOG_SUCCESS = "CREATE_BLOG_SUCCESS";
export const CREATE_BLOG_FAIL = "CREATE_BLOG_FAIL";
export const GET_MY_BLOGS_REQUEST = "GET_MY_BLOG_REQUEST";
export const GET_MY_BLOGS_SUCCESS = "GET_MY_BLOG_SUCCESS";
export const GET_MY_BLOGS_FAIL = "GET_MY_BLOG_FAIL";
