export const GET_ALL_SCHOOLS_REQUEST = "GET_ALL_SCHOOLS_REQUEST";
export const GET_ALL_SCHOOLS_SUCCESS = "GET_ALL_SCHOOLS_SUCCESS";
export const GET_ALL_SCHOOLS_FAIL = "GET_ALL_SCHOOLS_FAIL";
export const UPDATE_SCHOOL_REQUEST = "UPDATE_SCHOOL_REQUEST";
export const UPDATE_SCHOOL_SUCCESS = "UPDATE_SCHOOL_SUCCESS";
export const UPDATE_SCHOOL_FAIL = "UPDATE_SCHOOL_FAIL";
